// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { ReadAppointmentData, ReadAppointmentError, ReadAppointmentResponse2, ReadAppointmentsData, ReadAppointmentsResponse, CreateAppointmentData, CreateAppointmentError, CreateAppointmentResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Read Appointment
 */
export const readAppointment = <ThrowOnError extends boolean = false>(options: Options<ReadAppointmentData, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadAppointmentResponse2, ReadAppointmentError, ThrowOnError>({
        ...options,
        url: '/appointments/{appointment_id}'
    });
};

/**
 * Read Appointments
 * NOTE: Returns max 20 rows!
 */
export const readAppointments = <ThrowOnError extends boolean = false>(options?: Options<ReadAppointmentsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadAppointmentsResponse, unknown, ThrowOnError>({
        ...options,
        url: '/appointments'
    });
};

/**
 * Create Appointment
 */
export const createAppointment = <ThrowOnError extends boolean = false>(options: Options<CreateAppointmentData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateAppointmentResponse, CreateAppointmentError, ThrowOnError>({
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        },
        url: '/appointments'
    });
};