// This file is auto-generated by @hey-api/openapi-ts

export type CreateAppointment = {
    customer_freeform_name: string;
    customer_note: string;
    appt_at_freeform: string;
};

export type HttpError = {
    detail: string;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type ReadAppointmentResponse = {
    appointment_id: number;
    customer_freeform_name: string;
    customer_note: string;
    appt_at_freeform: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type ReadAppointmentData = {
    body?: never;
    path: {
        appointment_id: number;
    };
    query?: never;
    url: '/appointments/{appointment_id}';
};

export type ReadAppointmentErrors = {
    /**
     * Not Found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadAppointmentError = ReadAppointmentErrors[keyof ReadAppointmentErrors];

export type ReadAppointmentResponses = {
    /**
     * Successful Response
     */
    200: ReadAppointmentResponse;
};

export type ReadAppointmentResponse2 = ReadAppointmentResponses[keyof ReadAppointmentResponses];

export type ReadAppointmentsData = {
    body?: never;
    url: '/appointments';
};

export type ReadAppointmentsResponses = {
    /**
     * Successful Response
     */
    200: Array<ReadAppointmentResponse>;
};

export type ReadAppointmentsResponse = ReadAppointmentsResponses[keyof ReadAppointmentsResponses];

export type CreateAppointmentData = {
    body: CreateAppointment;
    url: '/appointments';
};

export type CreateAppointmentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAppointmentError = CreateAppointmentErrors[keyof CreateAppointmentErrors];

export type CreateAppointmentResponses = {
    /**
     * The created apointment ID
     */
    201: number;
};

export type CreateAppointmentResponse = CreateAppointmentResponses[keyof CreateAppointmentResponses];